### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'refresh')

### ISSUE THREAD

**Issue by IzliaB** [NetsoftHoldings/public-api-nodejs-demo#3]
I need your help, it turns out that I am trying to use the Hubstaff api. I am working in nodejs to make the connection, I followed the documentation (official hubstaff api documentation) and used the methods you have here from api.util

But I get the following error:
I need your help, it turns out that I am trying to use the Hubstaff api. I am working in nodejs to make the connection, I followed the documentation (official hubstaff api documentation) and used the methods you have here from api.util

But I get the following error:

![image](https://user-images.githubusercontent.com/22795826/179840008-c2ab5028-6b22-436f-8664-6d95c796a5e9.png)

 I don't know why this happens, and I can't find more examples of how I can implement this api. The openid-client lib is used to make the connection through the token and a state follow-up is carried out to refresh the token.

What I can do? Thank you in advance for your help

**Comment by urkle** [comment]
From that error it appears that your client object was never initialized.  Thus is nil.
